apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pool-local
  namespace: metallb-system
spec:
  addresses:
    - 10.0.1.100-10.0.1.150  # FAIXA DE IPS LIVRES DA SUA REDE

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: advert
  namespace: metallb-system
spec:
  ipAddressPools:
    - pool-local
