---
- name: Transferir e configurar kubeconfig do K3s
  hosts: labs
  become: true
  vars:
    kubeconfig_src: "/tmp/k3s.yaml"
    kubeconfig_dest: "/home/{{ ansible_user }}/.kube/config"
    kubeconfig_server: "https://10.0.10.10:6443"
    kubeconfig_context: "k3s-local-raspberry"
    kubeconfig_user: "k3s-local-raspberry"

  tasks:

    - name: Garantir pasta .kube existe no host labs
      file:
        path: "/home/{{ ansible_user }}/.kube"
        state: directory
        mode: '0755'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Copiar kubeconfig do Control Plane
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "{{ kubeconfig_src }}"
        flat: yes
      delegate_to: 10.0.10.10
      become: true
      run_once: true

    - name: Copiar kubeconfig para destino final do usuário labs
      copy:
        src: "{{ kubeconfig_src }}"
        dest: "{{ kubeconfig_dest }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0600'

    - name: Substituir IP do server no kubeconfig
      replace:
        path: "{{ kubeconfig_dest }}"
        regexp: '^\s+server: .*'
        replace: "    server: {{ kubeconfig_server }}"
        backup: yes

    - name: Substituir nome do cluster
      replace:
        path: "{{ kubeconfig_dest }}"
        regexp: '^\s+name: .*'
        replace: "  name: {{ kubeconfig_context }}"

    - name: Substituir nome do cluster no context
      replace:
        path: "{{ kubeconfig_dest }}"
        regexp: '^\s+cluster: .*'
        replace: "    cluster: {{ kubeconfig_context }}"

    - name: Substituir nome do user no context
      replace:
        path: "{{ kubeconfig_dest }}"
        regexp: '^\s+user: .*'
        replace: "    user: {{ kubeconfig_user }}"

    - name: Substituir nome do current-context
      replace:
        path: "{{ kubeconfig_dest }}"
        regexp: '^current-context: .*'
        replace: "current-context: {{ kubeconfig_context }}"

    - name: Substituir nome do user
      replace:
        path: "{{ kubeconfig_dest }}"
        regexp: '^- name: .*'
        replace: "- name: {{ kubeconfig_user }}"