---
- name: Obter kubeconfig no host remoto e copiar para local
  hosts: labs
  become: false
  gather_facts: false

  tasks:
    - name: Executar comando para obter kubeconfig
      ansible.builtin.shell: |
        cat ~/.kube/config > /tmp/kubeconfig_k3s_labs.txt
      args:
        executable: /bin/bash

    - name: Copiar arquivo de senha para máquina local
      ansible.builtin.fetch:
        src: /tmp/kubeconfig_k3s_labs.txt
        dest: ../kubeconfig_k3s_labs.txt
        flat: true
